#include "Core/Math/mathtypes.h"

REFLECT_STRUCT_BEGIN(IVec2)
REFLECT_STRUCT_MEMBER(x)
REFLECT_STRUCT_MEMBER(y)
REFLECT_STRUCT_END()

REFLECT_STRUCT_BEGIN(Mat4)
REFLECT_STRUCT_END()

REFLECT_STRUCT_BEGIN(Vec2)
REFLECT_STRUCT_MEMBER(x)
REFLECT_STRUCT_MEMBER(y)
REFLECT_STRUCT_END()

REFLECT_STRUCT_BEGIN(Vec3)
REFLECT_STRUCT_MEMBER(x)
REFLECT_STRUCT_MEMBER(y)
REFLECT_STRUCT_MEMBER(z)
REFLECT_STRUCT_END()

REFLECT_STRUCT_BEGIN(Quat)
REFLECT_STRUCT_MEMBER(x)
REFLECT_STRUCT_MEMBER(y)
REFLECT_STRUCT_MEMBER(z)
REFLECT_STRUCT_MEMBER(w)
REFLECT_STRUCT_END()
