# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  HeaderGenerator_config = debug
  Engine_config = debug
endif
ifeq ($(config),release)
  HeaderGenerator_config = release
  Engine_config = release
endif

PROJECTS := HeaderGenerator Engine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

HeaderGenerator:
ifneq (,$(HeaderGenerator_config))
	@echo "==== Building HeaderGenerator ($(HeaderGenerator_config)) ===="
	@${MAKE} --no-print-directory -C . -f HeaderGenerator.make config=$(HeaderGenerator_config)
endif

Engine: HeaderGenerator
ifneq (,$(Engine_config))
	@echo "==== Building Engine ($(Engine_config)) ===="
	@${MAKE} --no-print-directory -C . -f Engine.make config=$(Engine_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f HeaderGenerator.make clean
	@${MAKE} --no-print-directory -C . -f Engine.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   HeaderGenerator"
	@echo "   Engine"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"