#include "Keycodes.h"

std::unordered_map<std::string, Keycode> strToKeycode = {
    {"KC_0", KC_0},
    {"KC_1", KC_1},
    {"KC_2", KC_2},
    {"KC_3", KC_3},
    {"KC_4", KC_4},
    {"KC_5", KC_5},
    {"KC_6", KC_6},
    {"KC_7", KC_7},
    {"KC_8", KC_8},
    {"KC_9", KC_9},
    {"KC_a", KC_a},
    {"KC_ACBACK", KC_ACBACK},
    {"KC_ACBOOKMARKS", KC_ACBOOKMARKS},
    {"KC_ACFORWARD", KC_ACFORWARD},
    {"KC_ACHOME", KC_ACHOME},
    {"KC_ACREFRESH", KC_ACREFRESH},
    {"KC_ACSEARCH", KC_ACSEARCH},
    {"KC_ACSTOP", KC_ACSTOP},
    {"KC_AGAIN", KC_AGAIN},
    {"KC_ALTERASE", KC_ALTERASE},
    {"KC_QUOTE", KC_QUOTE},
    {"KC_APPLICATION", KC_APPLICATION},
    {"KC_AUDIOMUTE", KC_AUDIOMUTE},
    {"KC_AUDIONEXT", KC_AUDIONEXT},
    {"KC_AUDIOPLAY", KC_AUDIOPLAY},
    {"KC_AUDIOPREV", KC_AUDIOPREV},
    {"KC_AUDIOSTOP", KC_AUDIOSTOP},
    {"KC_b", KC_b},
    {"KC_BACKSLASH", KC_BACKSLASH},
    {"KC_BACKSPACE", KC_BACKSPACE},
    {"KC_BRIGHTNESSDOWN", KC_BRIGHTNESSDOWN},
    {"KC_BRIGHTNESSUP", KC_BRIGHTNESSUP},
    {"KC_c", KC_c},
    {"KC_CALCULATOR", KC_CALCULATOR},
    {"KC_CANCEL", KC_CANCEL},
    {"KC_CAPSLOCK", KC_CAPSLOCK},
    {"KC_CLEAR", KC_CLEAR},
    {"KC_CLEARAGAIN", KC_CLEARAGAIN},
    {"KC_COMMA", KC_COMMA},
    {"KC_COMPUTER", KC_COMPUTER},
    {"KC_COPY", KC_COPY},
    {"KC_CRSEL", KC_CRSEL},
    {"KC_CURRENCYSUBUNIT", KC_CURRENCYSUBUNIT},
    {"KC_CURRENCYUNIT", KC_CURRENCYUNIT},
    {"KC_CUT", KC_CUT},
    {"KC_d", KC_d},
    {"KC_DECIMALSEPARATOR", KC_DECIMALSEPARATOR},
    {"KC_DELETE", KC_DELETE},
    {"KC_DISPLAYSWITCH", KC_DISPLAYSWITCH},
    {"KC_DOWN", KC_DOWN},
    {"KC_e", KC_e},
    {"KC_EJECT", KC_EJECT},
    {"KC_END", KC_END},
    {"KC_EQUALS", KC_EQUALS},
    {"KC_ESCAPE", KC_ESCAPE},
    {"KC_EXECUTE", KC_EXECUTE},
    {"KC_EXSEL", KC_EXSEL},
    {"KC_f", KC_f},
    {"KC_F1", KC_F1},
    {"KC_F10", KC_F10},
    {"KC_F11", KC_F11},
    {"KC_F12", KC_F12},
    {"KC_F13", KC_F13},
    {"KC_F14", KC_F14},
    {"KC_F15", KC_F15},
    {"KC_F16", KC_F16},
    {"KC_F17", KC_F17},
    {"KC_F18", KC_F18},
    {"KC_F19", KC_F19},
    {"KC_F2", KC_F2},
    {"KC_F20", KC_F20},
    {"KC_F21", KC_F21},
    {"KC_F22", KC_F22},
    {"KC_F23", KC_F23},
    {"KC_F24", KC_F24},
    {"KC_F3", KC_F3},
    {"KC_F4", KC_F4},
    {"KC_F5", KC_F5},
    {"KC_F6", KC_F6},
    {"KC_F7", KC_F7},
    {"KC_F8", KC_F8},
    {"KC_F9", KC_F9},
    {"KC_FIND", KC_FIND},
    {"KC_g", KC_g},
    {"KC_BACKQUOTE", KC_BACKQUOTE},
    {"KC_h", KC_h},
    {"KC_HELP", KC_HELP},
    {"KC_HOME", KC_HOME},
    {"KC_i", KC_i},
    {"KC_INSERT", KC_INSERT},
    {"KC_j", KC_j},
    {"KC_k", KC_k},
    {"KC_KBDILLUMDOWN", KC_KBDILLUMDOWN},
    {"KC_KBDILLUMTOGGLE", KC_KBDILLUMTOGGLE},
    {"KC_KBDILLUMUP", KC_KBDILLUMUP},
    {"KC_KP0", KC_KP0},
    {"KC_KP00", KC_KP00},
    {"KC_KP000", KC_KP000},
    {"KC_KP1", KC_KP1},
    {"KC_KP2", KC_KP2},
    {"KC_KP3", KC_KP3},
    {"KC_KP4", KC_KP4},
    {"KC_KP5", KC_KP5},
    {"KC_KP6", KC_KP6},
    {"KC_KP7", KC_KP7},
    {"KC_KP8", KC_KP8},
    {"KC_KP9", KC_KP9},
    {"KC_KPA", KC_KPA},
    {"KC_KPAMPERSAND", KC_KPAMPERSAND},
    {"KC_KPAT", KC_KPAT},
    {"KC_KPB", KC_KPB},
    {"KC_KPBACKSPACE", KC_KPBACKSPACE},
    {"KC_KPBINARY", KC_KPBINARY},
    {"KC_KPC", KC_KPC},
    {"KC_KPCLEAR", KC_KPCLEAR},
    {"KC_KPCLEARENTRY", KC_KPCLEARENTRY},
    {"KC_KPCOLON", KC_KPCOLON},
    {"KC_KPCOMMA", KC_KPCOMMA},
    {"KC_KPD", KC_KPD},
    {"KC_KPDBLAMPERSAND", KC_KPDBLAMPERSAND},
    {"KC_KPDBLVERTICALBAR", KC_KPDBLVERTICALBAR},
    {"KC_KPDECIMAL", KC_KPDECIMAL},
    {"KC_KPDIVIDE", KC_KPDIVIDE},
    {"KC_KPE", KC_KPE},
    {"KC_KPENTER", KC_KPENTER},
    {"KC_KPEQUALS", KC_KPEQUALS},
    {"KC_KPEQUALSAS400", KC_KPEQUALSAS400},
    {"KC_KPEXCLAM", KC_KPEXCLAM},
    {"KC_KPF", KC_KPF},
    {"KC_KPGREATER", KC_KPGREATER},
    {"KC_KPHASH", KC_KPHASH},
    {"KC_KPHEXADECIMAL", KC_KPHEXADECIMAL},
    {"KC_KPLEFTBRACE", KC_KPLEFTBRACE},
    {"KC_KPLEFTPAREN", KC_KPLEFTPAREN},
    {"KC_KPLESS", KC_KPLESS},
    {"KC_KPMEMADD", KC_KPMEMADD},
    {"KC_KPMEMCLEAR", KC_KPMEMCLEAR},
    {"KC_KPMEMDIVIDE", KC_KPMEMDIVIDE},
    {"KC_KPMEMMULTIPLY", KC_KPMEMMULTIPLY},
    {"KC_KPMEMRECALL", KC_KPMEMRECALL},
    {"KC_KPMEMSTORE", KC_KPMEMSTORE},
    {"KC_KPMEMSUBTRACT", KC_KPMEMSUBTRACT},
    {"KC_KPMINUS", KC_KPMINUS},
    {"KC_KPMULTIPLY", KC_KPMULTIPLY},
    {"KC_KPOCTAL", KC_KPOCTAL},
    {"KC_KPPERCENT", KC_KPPERCENT},
    {"KC_KPPERIOD", KC_KPPERIOD},
    {"KC_KPPLUS", KC_KPPLUS},
    {"KC_KPPLUSMINUS", KC_KPPLUSMINUS},
    {"KC_KPPOWER", KC_KPPOWER},
    {"KC_KPRIGHTBRACE", KC_KPRIGHTBRACE},
    {"KC_KPRIGHTPAREN", KC_KPRIGHTPAREN},
    {"KC_KPSPACE", KC_KPSPACE},
    {"KC_KPTAB", KC_KPTAB},
    {"KC_KPVERTICALBAR", KC_KPVERTICALBAR},
    {"KC_KPXOR", KC_KPXOR},
    {"KC_l", KC_l},
    {"KC_LALT", KC_LALT},
    {"KC_LCTRL", KC_LCTRL},
    {"KC_LEFT", KC_LEFT},
    {"KC_LEFTBRACKET", KC_LEFTBRACKET},
    {"KC_LGUI", KC_LGUI},
    {"KC_LSHIFT", KC_LSHIFT},
    {"KC_m", KC_m},
    {"KC_MAIL", KC_MAIL},
    {"KC_MEDIASELECT", KC_MEDIASELECT},
    {"KC_MENU", KC_MENU},
    {"KC_MINUS", KC_MINUS},
    {"KC_MODE", KC_MODE},
    {"KC_MUTE", KC_MUTE},
    {"KC_n", KC_n},
    {"KC_NUMLOCKCLEAR", KC_NUMLOCKCLEAR},
    {"KC_o", KC_o},
    {"KC_OPER", KC_OPER},
    {"KC_OUT", KC_OUT},
    {"KC_p", KC_p},
    {"KC_PAGEDOWN", KC_PAGEDOWN},
    {"KC_PAGEUP", KC_PAGEUP},
    {"KC_PASTE", KC_PASTE},
    {"KC_PAUSE", KC_PAUSE},
    {"KC_PERIOD", KC_PERIOD},
    {"KC_POWER", KC_POWER},
    {"KC_PRINTSCREEN", KC_PRINTSCREEN},
    {"KC_PRIOR", KC_PRIOR},
    {"KC_q", KC_q},
    {"KC_r", KC_r},
    {"KC_RALT", KC_RALT},
    {"KC_RCTRL", KC_RCTRL},
    {"KC_RETURN", KC_RETURN},
    {"KC_RETURN2", KC_RETURN2},
    {"KC_RGUI", KC_RGUI},
    {"KC_RIGHT", KC_RIGHT},
    {"KC_RIGHTBRACKET", KC_RIGHTBRACKET},
    {"KC_RSHIFT", KC_RSHIFT},
    {"KC_s", KC_s},
    {"KC_SCROLLLOCK", KC_SCROLLLOCK},
    {"KC_SELECT", KC_SELECT},
    {"KC_SEMICOLON", KC_SEMICOLON},
    {"KC_SEPARATOR", KC_SEPARATOR},
    {"KC_SLASH", KC_SLASH},
    {"KC_SLEEP", KC_SLEEP},
    {"KC_SPACE", KC_SPACE},
    {"KC_STOP", KC_STOP},
    {"KC_SYSREQ", KC_SYSREQ},
    {"KC_t", KC_t},
    {"KC_TAB", KC_TAB},
    {"KC_THOUSANDSSEPARATOR", KC_THOUSANDSSEPARATOR},
    {"KC_u", KC_u},
    {"KC_UNDO", KC_UNDO},
    {"KC_UP", KC_UP},
    {"KC_v", KC_v},
    {"KC_VOLUMEDOWN", KC_VOLUMEDOWN},
    {"KC_VOLUMEUP", KC_VOLUMEUP},
    {"KC_w", KC_w},
    {"KC_WWW", KC_WWW},
    {"KC_x", KC_x},
    {"KC_y", KC_y},
    {"KC_z", KC_z},

    {"KC_MOUSE_LEFT", KC_MOUSE_LEFT},
    {"KC_MOUSE_MIDDLE", KC_MOUSE_MIDDLE},
    {"KC_MOUSE_RIGHT", KC_MOUSE_RIGHT},
    {"KC_MOUSE_X1", KC_MOUSE_X1},
    {"KC_MOUSE_X2", KC_MOUSE_X2},
};

std::unordered_map<Keycode, std::string, std::hash<int>> keycodeToStr = {
    {KC_0, "KC_0"},
    {KC_1, "KC_1"},
    {KC_2, "KC_2"},
    {KC_3, "KC_3"},
    {KC_4, "KC_4"},
    {KC_5, "KC_5"},
    {KC_6, "KC_6"},
    {KC_7, "KC_7"},
    {KC_8, "KC_8"},
    {KC_9, "KC_9"},
    {KC_a, "KC_a"},
    {KC_ACBACK, "KC_ACBACK"},
    {KC_ACBOOKMARKS, "KC_ACBOOKMARKS"},
    {KC_ACFORWARD, "KC_ACFORWARD"},
    {KC_ACHOME, "KC_ACHOME"},
    {KC_ACREFRESH, "KC_ACREFRESH"},
    {KC_ACSEARCH, "KC_ACSEARCH"},
    {KC_ACSTOP, "KC_ACSTOP"},
    {KC_AGAIN, "KC_AGAIN"},
    {KC_ALTERASE, "KC_ALTERASE"},
    {KC_QUOTE, "KC_QUOTE"},
    {KC_APPLICATION, "KC_APPLICATION"},
    {KC_AUDIOMUTE, "KC_AUDIOMUTE"},
    {KC_AUDIONEXT, "KC_AUDIONEXT"},
    {KC_AUDIOPLAY, "KC_AUDIOPLAY"},
    {KC_AUDIOPREV, "KC_AUDIOPREV"},
    {KC_AUDIOSTOP, "KC_AUDIOSTOP"},
    {KC_b, "KC_b"},
    {KC_BACKSLASH, "KC_BACKSLASH"},
    {KC_BACKSPACE, "KC_BACKSPACE"},
    {KC_BRIGHTNESSDOWN, "KC_BRIGHTNESSDOWN"},
    {KC_BRIGHTNESSUP, "KC_BRIGHTNESSUP"},
    {KC_c, "KC_c"},
    {KC_CALCULATOR, "KC_CALCULATOR"},
    {KC_CANCEL, "KC_CANCEL"},
    {KC_CAPSLOCK, "KC_CAPSLOCK"},
    {KC_CLEAR, "KC_CLEAR"},
    {KC_CLEARAGAIN, "KC_CLEARAGAIN"},
    {KC_COMMA, "KC_COMMA"},
    {KC_COMPUTER, "KC_COMPUTER"},
    {KC_COPY, "KC_COPY"},
    {KC_CRSEL, "KC_CRSEL"},
    {KC_CURRENCYSUBUNIT, "KC_CURRENCYSUBUNIT"},
    {KC_CURRENCYUNIT, "KC_CURRENCYUNIT"},
    {KC_CUT, "KC_CUT"},
    {KC_d, "KC_d"},
    {KC_DECIMALSEPARATOR, "KC_DECIMALSEPARATOR"},
    {KC_DELETE, "KC_DELETE"},
    {KC_DISPLAYSWITCH, "KC_DISPLAYSWITCH"},
    {KC_DOWN, "KC_DOWN"},
    {KC_e, "KC_e"},
    {KC_EJECT, "KC_EJECT"},
    {KC_END, "KC_END"},
    {KC_EQUALS, "KC_EQUALS"},
    {KC_ESCAPE, "KC_ESCAPE"},
    {KC_EXECUTE, "KC_EXECUTE"},
    {KC_EXSEL, "KC_EXSEL"},
    {KC_f, "KC_f"},
    {KC_F1, "KC_F1"},
    {KC_F10, "KC_F10"},
    {KC_F11, "KC_F11"},
    {KC_F12, "KC_F12"},
    {KC_F13, "KC_F13"},
    {KC_F14, "KC_F14"},
    {KC_F15, "KC_F15"},
    {KC_F16, "KC_F16"},
    {KC_F17, "KC_F17"},
    {KC_F18, "KC_F18"},
    {KC_F19, "KC_F19"},
    {KC_F2, "KC_F2"},
    {KC_F20, "KC_F20"},
    {KC_F21, "KC_F21"},
    {KC_F22, "KC_F22"},
    {KC_F23, "KC_F23"},
    {KC_F24, "KC_F24"},
    {KC_F3, "KC_F3"},
    {KC_F4, "KC_F4"},
    {KC_F5, "KC_F5"},
    {KC_F6, "KC_F6"},
    {KC_F7, "KC_F7"},
    {KC_F8, "KC_F8"},
    {KC_F9, "KC_F9"},
    {KC_FIND, "KC_FIND"},
    {KC_g, "KC_g"},
    {KC_BACKQUOTE, "KC_BACKQUOTE"},
    {KC_h, "KC_h"},
    {KC_HELP, "KC_HELP"},
    {KC_HOME, "KC_HOME"},
    {KC_i, "KC_i"},
    {KC_INSERT, "KC_INSERT"},
    {KC_j, "KC_j"},
    {KC_k, "KC_k"},
    {KC_KBDILLUMDOWN, "KC_KBDILLUMDOWN"},
    {KC_KBDILLUMTOGGLE, "KC_KBDILLUMTOGGLE"},
    {KC_KBDILLUMUP, "KC_KBDILLUMUP"},
    {KC_KP0, "KC_KP0"},
    {KC_KP00, "KC_KP00"},
    {KC_KP000, "KC_KP000"},
    {KC_KP1, "KC_KP1"},
    {KC_KP2, "KC_KP2"},
    {KC_KP3, "KC_KP3"},
    {KC_KP4, "KC_KP4"},
    {KC_KP5, "KC_KP5"},
    {KC_KP6, "KC_KP6"},
    {KC_KP7, "KC_KP7"},
    {KC_KP8, "KC_KP8"},
    {KC_KP9, "KC_KP9"},
    {KC_KPA, "KC_KPA"},
    {KC_KPAMPERSAND, "KC_KPAMPERSAND"},
    {KC_KPAT, "KC_KPAT"},
    {KC_KPB, "KC_KPB"},
    {KC_KPBACKSPACE, "KC_KPBACKSPACE"},
    {KC_KPBINARY, "KC_KPBINARY"},
    {KC_KPC, "KC_KPC"},
    {KC_KPCLEAR, "KC_KPCLEAR"},
    {KC_KPCLEARENTRY, "KC_KPCLEARENTRY"},
    {KC_KPCOLON, "KC_KPCOLON"},
    {KC_KPCOMMA, "KC_KPCOMMA"},
    {KC_KPD, "KC_KPD"},
    {KC_KPDBLAMPERSAND, "KC_KPDBLAMPERSAND"},
    {KC_KPDBLVERTICALBAR, "KC_KPDBLVERTICALBAR"},
    {KC_KPDECIMAL, "KC_KPDECIMAL"},
    {KC_KPDIVIDE, "KC_KPDIVIDE"},
    {KC_KPE, "KC_KPE"},
    {KC_KPENTER, "KC_KPENTER"},
    {KC_KPEQUALS, "KC_KPEQUALS"},
    {KC_KPEQUALSAS400, "KC_KPEQUALSAS400"},
    {KC_KPEXCLAM, "KC_KPEXCLAM"},
    {KC_KPF, "KC_KPF"},
    {KC_KPGREATER, "KC_KPGREATER"},
    {KC_KPHASH, "KC_KPHASH"},
    {KC_KPHEXADECIMAL, "KC_KPHEXADECIMAL"},
    {KC_KPLEFTBRACE, "KC_KPLEFTBRACE"},
    {KC_KPLEFTPAREN, "KC_KPLEFTPAREN"},
    {KC_KPLESS, "KC_KPLESS"},
    {KC_KPMEMADD, "KC_KPMEMADD"},
    {KC_KPMEMCLEAR, "KC_KPMEMCLEAR"},
    {KC_KPMEMDIVIDE, "KC_KPMEMDIVIDE"},
    {KC_KPMEMMULTIPLY, "KC_KPMEMMULTIPLY"},
    {KC_KPMEMRECALL, "KC_KPMEMRECALL"},
    {KC_KPMEMSTORE, "KC_KPMEMSTORE"},
    {KC_KPMEMSUBTRACT, "KC_KPMEMSUBTRACT"},
    {KC_KPMINUS, "KC_KPMINUS"},
    {KC_KPMULTIPLY, "KC_KPMULTIPLY"},
    {KC_KPOCTAL, "KC_KPOCTAL"},
    {KC_KPPERCENT, "KC_KPPERCENT"},
    {KC_KPPERIOD, "KC_KPPERIOD"},
    {KC_KPPLUS, "KC_KPPLUS"},
    {KC_KPPLUSMINUS, "KC_KPPLUSMINUS"},
    {KC_KPPOWER, "KC_KPPOWER"},
    {KC_KPRIGHTBRACE, "KC_KPRIGHTBRACE"},
    {KC_KPRIGHTPAREN, "KC_KPRIGHTPAREN"},
    {KC_KPSPACE, "KC_KPSPACE"},
    {KC_KPTAB, "KC_KPTAB"},
    {KC_KPVERTICALBAR, "KC_KPVERTICALBAR"},
    {KC_KPXOR, "KC_KPXOR"},
    {KC_l, "KC_l"},
    {KC_LALT, "KC_LALT"},
    {KC_LCTRL, "KC_LCTRL"},
    {KC_LEFT, "KC_LEFT"},
    {KC_LEFTBRACKET, "KC_LEFTBRACKET"},
    {KC_LGUI, "KC_LGUI"},
    {KC_LSHIFT, "KC_LSHIFT"},
    {KC_m, "KC_m"},
    {KC_MAIL, "KC_MAIL"},
    {KC_MEDIASELECT, "KC_MEDIASELECT"},
    {KC_MENU, "KC_MENU"},
    {KC_MINUS, "KC_MINUS"},
    {KC_MODE, "KC_MODE"},
    {KC_MUTE, "KC_MUTE"},
    {KC_n, "KC_n"},
    {KC_NUMLOCKCLEAR, "KC_NUMLOCKCLEAR"},
    {KC_o, "KC_o"},
    {KC_OPER, "KC_OPER"},
    {KC_OUT, "KC_OUT"},
    {KC_p, "KC_p"},
    {KC_PAGEDOWN, "KC_PAGEDOWN"},
    {KC_PAGEUP, "KC_PAGEUP"},
    {KC_PASTE, "KC_PASTE"},
    {KC_PAUSE, "KC_PAUSE"},
    {KC_PERIOD, "KC_PERIOD"},
    {KC_POWER, "KC_POWER"},
    {KC_PRINTSCREEN, "KC_PRINTSCREEN"},
    {KC_PRIOR, "KC_PRIOR"},
    {KC_q, "KC_q"},
    {KC_r, "KC_r"},
    {KC_RALT, "KC_RALT"},
    {KC_RCTRL, "KC_RCTRL"},
    {KC_RETURN, "KC_RETURN"},
    {KC_RETURN2, "KC_RETURN2"},
    {KC_RGUI, "KC_RGUI"},
    {KC_RIGHT, "KC_RIGHT"},
    {KC_RIGHTBRACKET, "KC_RIGHTBRACKET"},
    {KC_RSHIFT, "KC_RSHIFT"},
    {KC_s, "KC_s"},
    {KC_SCROLLLOCK, "KC_SCROLLLOCK"},
    {KC_SELECT, "KC_SELECT"},
    {KC_SEMICOLON, "KC_SEMICOLON"},
    {KC_SEPARATOR, "KC_SEPARATOR"},
    {KC_SLASH, "KC_SLASH"},
    {KC_SLEEP, "KC_SLEEP"},
    {KC_SPACE, "KC_SPACE"},
    {KC_STOP, "KC_STOP"},
    {KC_SYSREQ, "KC_SYSREQ"},
    {KC_t, "KC_t"},
    {KC_TAB, "KC_TAB"},
    {KC_THOUSANDSSEPARATOR, "KC_THOUSANDSSEPARATOR"},
    {KC_u, "KC_u"},
    {KC_UNDO, "KC_UNDO"},
    {KC_UP, "KC_UP"},
    {KC_v, "KC_v"},
    {KC_VOLUMEDOWN, "KC_VOLUMEDOWN"},
    {KC_VOLUMEUP, "KC_VOLUMEUP"},
    {KC_w, "KC_w"},
    {KC_WWW, "KC_WWW"},
    {KC_x, "KC_x"},
    {KC_y, "KC_y"},
    {KC_z, "KC_z"},

    {KC_MOUSE_LEFT, "KC_MOUSE_LEFT"},
    {KC_MOUSE_MIDDLE, "KC_MOUSE_MIDDLE"},
    {KC_MOUSE_RIGHT, "KC_MOUSE_RIGHT"},
    {KC_MOUSE_X1, "KC_MOUSE_X1"},
    {KC_MOUSE_X2, "KC_MOUSE_X2"},
};

std::vector<std::string> const & GetAllKeycodeStrings()
{
    static std::vector<std::string> allKeycodeStrings = {
        "KC_0",
        "KC_1",
        "KC_2",
        "KC_3",
        "KC_4",
        "KC_5",
        "KC_6",
        "KC_7",
        "KC_8",
        "KC_9",
        "KC_a",
        "KC_ACBACK",
        "KC_ACBOOKMARKS",
        "KC_ACFORWARD",
        "KC_ACHOME",
        "KC_ACREFRESH",
        "KC_ACSEARCH",
        "KC_ACSTOP",
        "KC_AGAIN",
        "KC_ALTERASE",
        "KC_QUOTE",
        "KC_APPLICATION",
        "KC_AUDIOMUTE",
        "KC_AUDIONEXT",
        "KC_AUDIOPLAY",
        "KC_AUDIOPREV",
        "KC_AUDIOSTOP",
        "KC_b",
        "KC_BACKSLASH",
        "KC_BACKSPACE",
        "KC_BRIGHTNESSDOWN",
        "KC_BRIGHTNESSUP",
        "KC_c",
        "KC_CALCULATOR",
        "KC_CANCEL",
        "KC_CAPSLOCK",
        "KC_CLEAR",
        "KC_CLEARAGAIN",
        "KC_COMMA",
        "KC_COMPUTER",
        "KC_COPY",
        "KC_CRSEL",
        "KC_CURRENCYSUBUNIT",
        "KC_CURRENCYUNIT",
        "KC_CUT",
        "KC_d",
        "KC_DECIMALSEPARATOR",
        "KC_DELETE",
        "KC_DISPLAYSWITCH",
        "KC_DOWN",
        "KC_e",
        "KC_EJECT",
        "KC_END",
        "KC_EQUALS",
        "KC_ESCAPE",
        "KC_EXECUTE",
        "KC_EXSEL",
        "KC_f",
        "KC_F1",
        "KC_F10",
        "KC_F11",
        "KC_F12",
        "KC_F13",
        "KC_F14",
        "KC_F15",
        "KC_F16",
        "KC_F17",
        "KC_F18",
        "KC_F19",
        "KC_F2",
        "KC_F20",
        "KC_F21",
        "KC_F22",
        "KC_F23",
        "KC_F24",
        "KC_F3",
        "KC_F4",
        "KC_F5",
        "KC_F6",
        "KC_F7",
        "KC_F8",
        "KC_F9",
        "KC_FIND",
        "KC_g",
        "KC_BACKQUOTE",
        "KC_h",
        "KC_HELP",
        "KC_HOME",
        "KC_i",
        "KC_INSERT",
        "KC_j",
        "KC_k",
        "KC_KBDILLUMDOWN",
        "KC_KBDILLUMTOGGLE",
        "KC_KBDILLUMUP",
        "KC_KP0",
        "KC_KP00",
        "KC_KP000",
        "KC_KP1",
        "KC_KP2",
        "KC_KP3",
        "KC_KP4",
        "KC_KP5",
        "KC_KP6",
        "KC_KP7",
        "KC_KP8",
        "KC_KP9",
        "KC_KPA",
        "KC_KPAMPERSAND",
        "KC_KPAT",
        "KC_KPB",
        "KC_KPBACKSPACE",
        "KC_KPBINARY",
        "KC_KPC",
        "KC_KPCLEAR",
        "KC_KPCLEARENTRY",
        "KC_KPCOLON",
        "KC_KPCOMMA",
        "KC_KPD",
        "KC_KPDBLAMPERSAND",
        "KC_KPDBLVERTICALBAR",
        "KC_KPDECIMAL",
        "KC_KPDIVIDE",
        "KC_KPE",
        "KC_KPENTER",
        "KC_KPEQUALS",
        "KC_KPEQUALSAS400",
        "KC_KPEXCLAM",
        "KC_KPF",
        "KC_KPGREATER",
        "KC_KPHASH",
        "KC_KPHEXADECIMAL",
        "KC_KPLEFTBRACE",
        "KC_KPLEFTPAREN",
        "KC_KPLESS",
        "KC_KPMEMADD",
        "KC_KPMEMCLEAR",
        "KC_KPMEMDIVIDE",
        "KC_KPMEMMULTIPLY",
        "KC_KPMEMRECALL",
        "KC_KPMEMSTORE",
        "KC_KPMEMSUBTRACT",
        "KC_KPMINUS",
        "KC_KPMULTIPLY",
        "KC_KPOCTAL",
        "KC_KPPERCENT",
        "KC_KPPERIOD",
        "KC_KPPLUS",
        "KC_KPPLUSMINUS",
        "KC_KPPOWER",
        "KC_KPRIGHTBRACE",
        "KC_KPRIGHTPAREN",
        "KC_KPSPACE",
        "KC_KPTAB",
        "KC_KPVERTICALBAR",
        "KC_KPXOR",
        "KC_l",
        "KC_LALT",
        "KC_LCTRL",
        "KC_LEFT",
        "KC_LEFTBRACKET",
        "KC_LGUI",
        "KC_LSHIFT",
        "KC_m",
        "KC_MAIL",
        "KC_MEDIASELECT",
        "KC_MENU",
        "KC_MINUS",
        "KC_MODE",
        "KC_MUTE",
        "KC_n",
        "KC_NUMLOCKCLEAR",
        "KC_o",
        "KC_OPER",
        "KC_OUT",
        "KC_p",
        "KC_PAGEDOWN",
        "KC_PAGEUP",
        "KC_PASTE",
        "KC_PAUSE",
        "KC_PERIOD",
        "KC_POWER",
        "KC_PRINTSCREEN",
        "KC_PRIOR",
        "KC_q",
        "KC_r",
        "KC_RALT",
        "KC_RCTRL",
        "KC_RETURN",
        "KC_RETURN2",
        "KC_RGUI",
        "KC_RIGHT",
        "KC_RIGHTBRACKET",
        "KC_RSHIFT",
        "KC_s",
        "KC_SCROLLLOCK",
        "KC_SELECT",
        "KC_SEMICOLON",
        "KC_SEPARATOR",
        "KC_SLASH",
        "KC_SLEEP",
        "KC_SPACE",
        "KC_STOP",
        "KC_SYSREQ",
        "KC_t",
        "KC_TAB",
        "KC_THOUSANDSSEPARATOR",
        "KC_u",
        "KC_UNDO",
        "KC_UP",
        "KC_v",
        "KC_VOLUMEDOWN",
        "KC_VOLUMEUP",
        "KC_w",
        "KC_WWW",
        "KC_x",
        "KC_y",
        "KC_z",

        "KC_MOUSE_LEFT",
        "KC_MOUSE_MIDDLE",
        "KC_MOUSE_RIGHT",
        "KC_MOUSE_X1",
        "KC_MOUSE_X2",
    };
    return allKeycodeStrings;
}